<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A2S9SMV" failures="1" tests="1" name="OtpTest" time="166.636" errors="0" timestamp="2024-02-02T17:44:37 IST">
  <testcase classname="com.oneapp.test_suits.OtpTestCases" name="TC101_ValidOtpTestcase" time="93.875">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Resend OTP in] but found [Resend]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Resend OTP in] but found [Resend]
at com.oneapp.test_suits.OtpTestCases.TC101_ValidOtpTestcase(OtpTestCases.java:126)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC101_ValidOtpTestcase -->
</testsuite> <!-- OtpTest -->
